package bushuk.stanislau.bitbucketproject.constants

object ListOfLanguages {
    fun listOfLanguages(): MutableList<String> = mutableListOf(
            "All",
            "typeScript",
            "pureBasic",
            "objective-C++",
            "dart",
            "shell",
            "SAS",
            "Kotlin",
            "objective-c",
            "ruby",
            "go",
            "Visual Basic",
            "PHP",
            "java",
            "scala",
            "perl",
            "lua",
            "vue",
            "CoffeeScript",
            "html/css",
            "swift",
            "c",
            "rust",
            "Assembly",
            "c#",
            "CSS",
            "ActionScript",
            "javascript",
            "R",
            "Erlang",
            "python",
            "groovy",
            "haskell",
            "c++")
}